services:
    cc-app:
        image: cc-app
        container_name: cc-app
        restart: unless-stopped
        build:
          context: .
        depends_on:
        - cc-db
        env_file:
          - .env
        ports:
          - "3000:3000"
    cc-db:
        image: postgres:14-alpine
        restart: always
        environment:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_DB: ${DATABASE_NAME}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}     
        volumes:
          - cc-pgdata:/var/lib/postgresql/data
        # ports:
        #   - "5436:5432"
volumes:
  cc-pgdata:
    external: true
